### ISSUE TITLE
Bot unable to complete prune request if it is unable to send messages

### ISSUE THREAD

**Issue by Zolhungaj** [r-anime/ZeroTsu#67]
**Describe the bug**
Using the prune command in a channel where the bot is not allowed to send messages will result in a failure. Even though this message is not strictly needed and will often not even be seen before the prune happens. 

**To Reproduce**
1. Remove the send messages permission from the bot for a channel
2. Use the prune command
3. Bot will be unwilling to prune

**Expected behavior**
Pruning as usual, just without the bot saying that it is fetching messages.

**Comment by apiks** [comment]
Issue cannot be replicated. Has likely been resolved over the past years via slash commands.
