### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by Hamsterland** [r-anime/ZeroTsu#68]
Is there an official Discord server for the bot? I have some questions about the architecture that would be cool to ask in general, as well ask talk about some code.

**Comment by apiks** [comment]
Yes, the official support server for ZeroTsu is https://discord.gg/BDT8Twv. If your questions are about some rather questionable design decisions and a lot of inefficiencies in the code, they're known but cannot be overhauled due to time constraints. I can explain whatever you want to ask.
